# Libraries
#
usr/lib/lib*.so.*

# Services
#
usr/sbin/cluckd

# Tools
#
usr/bin/cluck-status

# Configuration Files
#
conf/cluckd.conf                                  etc/cluck/
conf/README.md                                    etc/cluck/cluck.d/
conf/logger/cluckd.conf                           etc/cluck/logger/
conf/logger/README.md                             etc/cluck/logger/cluckd.d/
usr/share/communicatord
usr/share/snaplogger
usr/share/eventdispatcher
